version: '3.7'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./config/collector.yml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml
      # depends_on:
    ports:
      - 4318:4318
      - 4317:4317
